- job:
    name: python-mistralclient-devstack-dsvm
    parent: legacy-dsvm-base
    run: playbooks/legacy/python-mistralclient-devstack-dsvm/run.yaml
    post-run: playbooks/legacy/python-mistralclient-devstack-dsvm/post.yaml
    timeout: 4200
    required-projects:
      - openstack/devstack
      - openstack/devstack-gate
      - openstack/heat
      - openstack/mistral
      - openstack/mistral-dashboard
      - openstack/python-mistralclient

- project:
    templates:
      - openstack-python-jobs
      - openstack-python35-jobs
      - check-requirements
      - openstackclient-plugin-jobs
      - publish-openstack-sphinx-docs
      - release-notes-jobs
    check:
      jobs:
        - python-mistralclient-devstack-dsvm
        - openstack-tox-cover:
            voting: false
    gate:
      jobs:
        - python-mistralclient-devstack-dsvm

